#file cd.yml
name: Continuous Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: tensile-core-474113-t6
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and push Docker image
        run: |
          docker build --platform=linux/amd64 -t us-central1-docker.pkg.dev/tensile-core-474113-t6/notely-ar-repo/notely:latest .
          docker push us-central1-docker.pkg.dev/tensile-core-474113-t6/notely-ar-repo/notely:latest
